# Generated by Django 5.0.3 on 2024-09-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMI_Calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='user',
        ),
    ]
